PILLARS = [
    {
        "name": "Full-Stack Observability",
        "description": "Assess your organization's maturity in monitoring, observability, and incident management across the full stack.",
        "overall_weight": 1.0,
        "display_order": 1,
        "is_active": True,
        "is_gated": False,
        "gate_question": None,
        "questions": [
            {
                "text": "How would you describe your organization's current approach to monitoring production systems?",
                "weight": 1.5,
                "general": True,
                "display_order": 1,
                "context_tags": [],
                "options": [
                    (1, "We react to issues only when customers or operations report them"),
                    (2, "We have basic uptime monitoring and some manual dashboards"),
                    (3, "We collect metrics, logs, and traces and can correlate issues across services"),
                    (4, "Unified, proactive observability with automatic anomaly detection and full-stack visibility"),
                ],
                "personas": [],
            },
            {
                "text": "What percentage of your production services have any form of monitoring today?",
                "weight": 1.0,
                "general": True,
                "display_order": 2,
                "context_tags": [],
                "options": [
                    (1, "Less than 25%"),
                    (2, "25–50%"),
                    (3, "50–80%"),
                    (4, "More than 80% with standardized monitoring across all environments"),
                ],
                "personas": [],
            },
            {
                "text": "How does your team currently get notified about production incidents?",
                "weight": 1.5,
                "general": True,
                "display_order": 3,
                "context_tags": [],
                "options": [
                    (1, "Customers tell us, or we notice manually"),
                    (2, "Basic threshold alerts via email or Slack"),
                    (3, "Alerting with on-call rotation and runbooks, but still high noise"),
                    (4, "Intelligent alerting with noise reduction, on-call routing, and automated runbooks"),
                ],
                "personas": [],
            },
            {
                "text": "How are your infrastructure, application, and user experience monitoring tools managed?",
                "weight": 1.0,
                "general": True,
                "display_order": 4,
                "context_tags": [],
                "options": [
                    (1, "Each team uses different tools with no central view"),
                    (2, "Some consolidation but still multiple disconnected tools"),
                    (3, "Most teams use a shared platform with unified dashboards"),
                    (4, "Single observability platform with full-stack correlation from infrastructure to end-user experience"),
                ],
                "personas": [],
            },
            {
                "text": "Does your organization have defined Service Level Objectives (SLOs)?",
                "weight": 2.0,
                "general": False,
                "display_order": 5,
                "context_tags": [],
                "options": [
                    (1, "No SLOs defined internally"),
                    (2, "SLOs exist informally or only for a few services"),
                    (3, "SLOs defined for major services with error budgets tracked"),
                    (4, "SLOs for all critical services with automated error budget burn alerting and reporting"),
                ],
                "personas": [("sre_platform_engineer", 1.2)],
            },
            {
                "text": "What percentage of your services have distributed tracing implemented end-to-end?",
                "weight": 1.5,
                "general": False,
                "display_order": 6,
                "context_tags": ["microservices", "kubernetes", "cloud_native"],
                "options": [
                    (1, "0% — no distributed tracing"),
                    (2, "Less than 25% (critical paths only)"),
                    (3, "25–75% of services"),
                    (4, "More than 75% with full service dependency mapping"),
                ],
                "personas": [("sre_platform_engineer", 1.2), ("devops_engineer", 1.2)],
            },
            {
                "text": "What is your team's typical Mean Time to Resolve (MTTR) for P1 incidents?",
                "weight": 1.5,
                "general": False,
                "display_order": 7,
                "context_tags": [],
                "options": [
                    (1, "More than 4 hours"),
                    (2, "1–4 hours"),
                    (3, "30 minutes to 1 hour"),
                    (4, "Less than 30 minutes with AI-assisted investigation"),
                ],
                "personas": [("sre_platform_engineer", 1.2)],
            },
            {
                "text": "How is your infrastructure currently managed?",
                "weight": 1.0,
                "general": False,
                "display_order": 8,
                "context_tags": ["aws", "gcp", "azure", "terraform", "infrastructure"],
                "options": [
                    (1, "Manual provisioning with no version control"),
                    (2, "Some scripting but infrastructure changes are not consistently tracked"),
                    (3, "Infrastructure as Code (Terraform, CloudFormation) for most resources"),
                    (4, "Full GitOps with automated drift detection and policy enforcement"),
                ],
                "personas": [("sre_platform_engineer", 1.1), ("devops_engineer", 1.1)],
            },
            {
                "text": "How mature is your CI/CD pipeline?",
                "weight": 1.5,
                "general": False,
                "display_order": 9,
                "context_tags": ["ci_cd", "devops", "github", "gitlab"],
                "options": [
                    (1, "Manual deployments with no pipeline"),
                    (2, "Basic pipeline for some services, manual steps still required"),
                    (3, "Automated CI/CD with deployment gates and test integration"),
                    (4, "Full pipeline automation with feature flags, canary deployments, and automated rollbacks"),
                ],
                "personas": [("devops_engineer", 1.2)],
            },
            {
                "text": "How do you monitor your CI/CD pipeline health and deployment performance?",
                "weight": 1.0,
                "general": False,
                "display_order": 10,
                "context_tags": [],
                "options": [
                    (1, "We don't monitor pipelines"),
                    (2, "Basic success/fail notifications"),
                    (3, "Pipeline metrics tracked with DORA-style reporting"),
                    (4, "Full DORA metrics (deployment frequency, lead time, MTTR, change failure rate) with trend analysis"),
                ],
                "personas": [("devops_engineer", 1.1)],
            },
            {
                "text": "How does your organization approach platform engineering and developer self-service?",
                "weight": 2.0,
                "general": False,
                "display_order": 11,
                "context_tags": [],
                "options": [
                    (1, "No internal platform — each team provisions its own infrastructure"),
                    (2, "Shared scripts and runbooks but no self-service capability"),
                    (3, "Internal platform with self-service for common workflows"),
                    (4, "Full Internal Developer Platform with golden paths, service catalog, and automated onboarding"),
                ],
                "personas": [("cto_executive", 0.9), ("vp_engineering", 0.9)],
            },
            {
                "text": "How do you monitor end-user experience in production?",
                "weight": 1.5,
                "general": False,
                "display_order": 12,
                "context_tags": [],
                "options": [
                    (1, "We don't actively monitor end-user experience"),
                    (2, "Server-side error tracking only"),
                    (3, "Real User Monitoring (RUM) for web applications"),
                    (4, "Full digital experience monitoring: RUM, Synthetic testing, mobile monitoring, and session replay"),
                ],
                "personas": [("cto_executive", 0.9), ("vp_engineering", 0.9)],
            },
            {
                "text": "How does your team instrument application code for observability?",
                "weight": 1.0,
                "general": False,
                "display_order": 13,
                "context_tags": [],
                "options": [
                    (1, "No instrumentation — we rely on logs only"),
                    (2, "Basic logging with some manual metrics"),
                    (3, "Structured logging, custom metrics, and basic APM integration"),
                    (4, "Auto-instrumentation with custom spans, business metrics, and distributed context propagation"),
                ],
                "personas": [("software_developer", 1.0)],
            },
            {
                "text": "How do you monitor AI/ML models in production?",
                "weight": 1.0,
                "general": False,
                "display_order": 14,
                "context_tags": [],
                "options": [
                    (1, "We don't monitor models post-deployment"),
                    (2, "Basic uptime and error rate monitoring only"),
                    (3, "Performance metrics tracked (latency, throughput) but not model quality"),
                    (4, "Full model observability: latency, drift, accuracy degradation, and business impact metrics"),
                ],
                "personas": [("ml_ai_engineer", 1.0)],
            },
            {
                "text": "How is security visibility integrated into your observability platform?",
                "weight": 1.0,
                "general": False,
                "display_order": 15,
                "context_tags": [],
                "options": [
                    (1, "Security monitoring is completely separate from operational observability"),
                    (2, "Some log correlation between security and ops tools"),
                    (3, "Security events visible in the same platform used by engineering"),
                    (4, "Unified security and operational observability with correlated threat detection and audit trails"),
                ],
                "personas": [("ciso_vp_security", 1.0), ("security_engineer", 1.0)],
            },
        ],
    },
    {
        "name": "AIOps & Intelligent Observability",
        "description": "Assess your organization's maturity in applying AI and machine learning to observability and incident management workflows.",
        "overall_weight": 0.9,
        "display_order": 2,
        "is_active": True,
        "is_gated": False,
        "gate_question": None,
        "questions": [
            {
                "text": "How does your team currently handle alert noise and alert fatigue?",
                "weight": 2.0,
                "general": True,
                "display_order": 1,
                "context_tags": [],
                "options": [
                    (1, "We receive a high volume of alerts and triage manually — alert fatigue is a serious problem"),
                    (2, "We've manually tuned some thresholds but alert noise is still significant"),
                    (3, "Alerts are grouped and prioritized; on-call burden is manageable"),
                    (4, "AI/ML-powered alert correlation with automated noise reduction and intelligent grouping"),
                ],
                "personas": [],
            },
            {
                "text": "How does your organization detect anomalies in production systems?",
                "weight": 1.5,
                "general": True,
                "display_order": 2,
                "context_tags": [],
                "options": [
                    (1, "Manual investigation after an incident is reported"),
                    (2, "Static threshold-based alerts only"),
                    (3, "Dynamic thresholds with some baseline comparison"),
                    (4, "ML-based anomaly detection with automatic root cause analysis and correlated signals"),
                ],
                "personas": [],
            },
            {
                "text": "How much of your incident investigation process is automated today?",
                "weight": 1.0,
                "general": True,
                "display_order": 3,
                "context_tags": [],
                "options": [
                    (1, "Fully manual — engineers investigate everything from scratch"),
                    (2, "We have runbooks but execution is manual"),
                    (3, "Some automated diagnostics (log search, metric snapshots) triggered by alerts"),
                    (4, "AI-assisted investigation that surfaces probable root cause, impacted services, and suggested remediation automatically"),
                ],
                "personas": [],
            },
            {
                "text": "How do you currently correlate events across your infrastructure and applications to identify root cause?",
                "weight": 1.5,
                "general": True,
                "display_order": 4,
                "context_tags": [],
                "options": [
                    (1, "We don't — teams investigate in silos using separate tools"),
                    (2, "Manual correlation across multiple dashboards during incidents"),
                    (3, "Some automated event correlation within our observability platform"),
                    (4, "AI-driven unified correlation across metrics, traces, logs, and events with automatic service impact mapping"),
                ],
                "personas": [],
            },
            {
                "text": "Does your team use AI or ML-powered features to automatically detect, triage, or resolve incidents?",
                "weight": 2.0,
                "general": False,
                "display_order": 5,
                "context_tags": ["aiops", "machine_learning", "ai"],
                "options": [
                    (1, "No AI/ML in our incident workflows"),
                    (2, "We are evaluating or piloting AI tools"),
                    (3, "AI tools are used by some teams for specific tasks"),
                    (4, "AI-assisted workflows are standard: automatic triage, probable root cause, and suggested remediation are part of every incident"),
                ],
                "personas": [("sre_platform_engineer", 1.2)],
            },
            {
                "text": "How are on-call handoffs and incident context documented?",
                "weight": 1.5,
                "general": False,
                "display_order": 6,
                "context_tags": [],
                "options": [
                    (1, "Ad-hoc — engineers write notes in chat or nowhere"),
                    (2, "Incident tickets created manually with basic information"),
                    (3, "Structured incident records with timeline, affected services, and resolution steps"),
                    (4, "AI-generated incident summaries with automated postmortem drafts and action item tracking"),
                ],
                "personas": [("sre_platform_engineer", 1.2)],
            },
            {
                "text": "How do you use historical incident data to prevent future incidents?",
                "weight": 1.0,
                "general": False,
                "display_order": 7,
                "context_tags": [],
                "options": [
                    (1, "We don't systematically use historical data"),
                    (2, "Manual postmortems, but insights rarely feed back into monitoring improvements"),
                    (3, "Postmortem action items are tracked and some monitoring improvements result"),
                    (4, "AI analysis of historical incidents drives proactive monitoring and automated remediation playbooks"),
                ],
                "personas": [("sre_platform_engineer", 1.1), ("devops_engineer", 1.1)],
            },
            {
                "text": "How does your organization measure the business impact of observability investments?",
                "weight": 1.5,
                "general": False,
                "display_order": 8,
                "context_tags": [],
                "options": [
                    (1, "We don't measure ROI on observability"),
                    (2, "Anecdotal feedback from engineering teams only"),
                    (3, "MTTR and incident frequency are tracked and improving"),
                    (4, "Full business impact measurement: MTTR, change failure rate, customer impact hours, and revenue impact correlated with observability maturity"),
                ],
                "personas": [("cto_executive", 0.9), ("vp_engineering", 0.9)],
            },
            {
                "text": "To what extent does your organization use AIOps to proactively prevent incidents before they occur?",
                "weight": 1.0,
                "general": False,
                "display_order": 9,
                "context_tags": [],
                "options": [
                    (1, "We don't use AI for proactive monitoring"),
                    (2, "Basic capacity planning using historical metrics"),
                    (3, "Predictive alerting for known patterns (traffic spikes, disk fill)"),
                    (4, "AI-powered proactive incident prevention with forecasting, anomaly prediction, and automated remediation"),
                ],
                "personas": [("cto_executive", 0.9), ("vp_engineering", 0.9)],
            },
            {
                "text": "How does your deployment pipeline integrate with your observability platform?",
                "weight": 1.0,
                "general": False,
                "display_order": 10,
                "context_tags": [],
                "options": [
                    (1, "No integration — deployments and monitoring are completely separate"),
                    (2, "Deployment events are manually correlated with monitoring during incidents"),
                    (3, "Deployment markers are visible in monitoring dashboards for correlation"),
                    (4, "Full deployment intelligence: automated canary analysis, deployment-correlated anomaly detection, and automatic rollback triggers"),
                ],
                "personas": [("devops_engineer", 1.1)],
            },
            {
                "text": "Have you used AI-powered tools to help debug or diagnose production issues?",
                "weight": 1.0,
                "general": False,
                "display_order": 11,
                "context_tags": [],
                "options": [
                    (1, "Never — we debug manually using logs and dashboards"),
                    (2, "Occasionally, but not as a standard practice"),
                    (3, "AI debugging tools are available and used by most engineers"),
                    (4, "AI-assisted debugging is standard: natural language log search, AI-suggested fixes, and code-correlated tracing"),
                ],
                "personas": [("software_developer", 1.0)],
            },
            {
                "text": "How does your team use ML to optimize your observability data pipeline (log parsing, intelligent sampling)?",
                "weight": 1.5,
                "general": False,
                "display_order": 12,
                "context_tags": [],
                "options": [
                    (1, "We don't use ML in our observability data pipeline"),
                    (2, "Basic automated log parsing only"),
                    (3, "Intelligent sampling and dynamic retention policies in place"),
                    (4, "Full ML-driven pipeline: adaptive sampling, intelligent log pattern extraction, and cost-optimized data retention"),
                ],
                "personas": [("ml_ai_engineer", 1.1)],
            },
        ],
    },
    {
        "name": "AI Application Observability",
        "description": "Assess your organization's maturity in monitoring, evaluating, and governing AI systems and LLM-powered applications in production.",
        "overall_weight": 0.85,
        "display_order": 3,
        "is_active": True,
        "is_gated": True,
        "gate_question": "Is your organization currently building, deploying, or operating AI-powered applications or services?",
        "questions": [
            {
                "text": "How do you currently monitor the behavior and performance of your LLM-powered applications in production?",
                "weight": 2.0,
                "general": True,
                "display_order": 1,
                "context_tags": [],
                "options": [
                    (1, "We don't monitor LLM applications beyond basic uptime"),
                    (2, "We track API error rates and latency only"),
                    (3, "We track LLM-specific metrics: token usage, latency per call, and cost per request"),
                    (4, "Full LLM observability: request tracing, prompt/response logging, cost tracking, quality scoring, and drift detection"),
                ],
                "personas": [],
            },
            {
                "text": "How do you detect and respond to quality degradation in your AI systems (hallucinations, accuracy drift)?",
                "weight": 1.5,
                "general": True,
                "display_order": 2,
                "context_tags": [],
                "options": [
                    (1, "We don't — issues are discovered by end users reporting problems"),
                    (2, "Manual review of a sample of LLM outputs periodically"),
                    (3, "Automated evaluation pipeline for a subset of critical outputs"),
                    (4, "Continuous automated quality evaluation with drift detection, alerting, and version-correlated analysis"),
                ],
                "personas": [],
            },
            {
                "text": "How do you currently track and optimize the cost of running your LLM applications?",
                "weight": 1.5,
                "general": True,
                "display_order": 3,
                "context_tags": [],
                "options": [
                    (1, "We don't track LLM costs beyond the monthly invoice"),
                    (2, "High-level cost tracking by service or team"),
                    (3, "Per-request cost tracking with optimization guidelines"),
                    (4, "Real-time cost optimization: per-user, per-feature, per-model cost tracking with automated budget alerting and model routing"),
                ],
                "personas": [],
            },
            {
                "text": "How do you manage and version prompts in your LLM applications?",
                "weight": 1.0,
                "general": True,
                "display_order": 4,
                "context_tags": [],
                "options": [
                    (1, "Prompts are hardcoded with no version control"),
                    (2, "Prompts are stored in config files with basic version control"),
                    (3, "Prompt versioning with A/B testing capabilities"),
                    (4, "Full prompt lifecycle management: versioned, tested, evaluated, and deployed with CI/CD integration"),
                ],
                "personas": [],
            },
            {
                "text": "How do you trace and debug requests through your AI agent or LLM pipeline?",
                "weight": 2.0,
                "general": False,
                "display_order": 5,
                "context_tags": ["llm", "ai_agents", "langchain", "openai", "anthropic"],
                "options": [
                    (1, "No tracing — we log inputs and outputs only"),
                    (2, "Basic logging at entry and exit points of the pipeline"),
                    (3, "Step-level tracing of agent actions and LLM calls"),
                    (4, "Full distributed tracing across agent steps, tool calls, and LLM requests with latency breakdown and token attribution"),
                ],
                "personas": [("ml_ai_engineer", 1.2)],
            },
            {
                "text": "How do you evaluate and benchmark your LLM models or pipelines before deploying changes?",
                "weight": 1.5,
                "general": False,
                "display_order": 6,
                "context_tags": [],
                "options": [
                    (1, "Manual testing of a few example inputs"),
                    (2, "Basic regression tests against expected outputs"),
                    (3, "Automated evaluation suite with defined quality metrics"),
                    (4, "Continuous evaluation pipeline with automated benchmarking, regression detection, and human-in-the-loop review for significant changes"),
                ],
                "personas": [("ml_ai_engineer", 1.2)],
            },
            {
                "text": "How do you manage the lifecycle of AI agents (deployment, versioning, rollback)?",
                "weight": 1.0,
                "general": False,
                "display_order": 7,
                "context_tags": [],
                "options": [
                    (1, "No formal lifecycle management"),
                    (2, "Manual deployment with basic version tracking"),
                    (3, "Automated deployment with versioning and staged rollouts"),
                    (4, "Full MLOps for agents: automated CI/CD, canary deployments, and automated rollback triggered by quality or performance degradation"),
                ],
                "personas": [("ml_ai_engineer", 1.1), ("devops_engineer", 1.1)],
            },
            {
                "text": "How does your organization govern AI and LLM use in production applications (safety, compliance, data privacy)?",
                "weight": 1.5,
                "general": False,
                "display_order": 8,
                "context_tags": [],
                "options": [
                    (1, "No formal AI governance"),
                    (2, "Informal guidelines exist but are not enforced"),
                    (3, "Documented AI policies with security review for new AI features"),
                    (4, "Formal AI governance framework: PII detection in prompts/responses, model access controls, audit logging, and compliance reporting"),
                ],
                "personas": [("cto_executive", 0.9), ("vp_engineering", 0.9)],
            },
            {
                "text": "How do you measure the business impact of your AI-powered features?",
                "weight": 1.0,
                "general": False,
                "display_order": 9,
                "context_tags": [],
                "options": [
                    (1, "We don't track AI-specific business metrics"),
                    (2, "Basic usage metrics only (requests, active users)"),
                    (3, "Feature-level metrics tied to business outcomes"),
                    (4, "Full AI ROI measurement: quality scores, user satisfaction, cost per value delivered, and business outcome correlation"),
                ],
                "personas": [("cto_executive", 0.9), ("vp_engineering", 0.9)],
            },
            {
                "text": "How do you test AI-powered features during development before deploying to production?",
                "weight": 1.0,
                "general": False,
                "display_order": 10,
                "context_tags": [],
                "options": [
                    (1, "Manual testing only with a few example inputs"),
                    (2, "Unit tests for non-AI components, manual validation for AI behavior"),
                    (3, "Automated tests with fixed test cases for AI components"),
                    (4, "Property-based testing and automated LLM evaluation integrated into CI pipeline"),
                ],
                "personas": [("software_developer", 1.0)],
            },
            {
                "text": "How do you handle reliability for AI services that depend on external LLM APIs?",
                "weight": 1.5,
                "general": False,
                "display_order": 11,
                "context_tags": [],
                "options": [
                    (1, "No fallback — if the API is down, the feature is down"),
                    (2, "Basic error handling and user-facing error messages"),
                    (3, "Retry logic and fallback to degraded mode"),
                    (4, "Multi-provider routing with automatic failover, circuit breakers, and graceful degradation"),
                ],
                "personas": [("sre_platform_engineer", 1.1), ("devops_engineer", 1.1)],
            },
            {
                "text": "How is the infrastructure for your AI workloads managed and scaled?",
                "weight": 1.0,
                "general": False,
                "display_order": 12,
                "context_tags": [],
                "options": [
                    (1, "Manual, ad-hoc provisioning"),
                    (2, "Fixed infrastructure with manual scaling"),
                    (3, "Auto-scaling configured for AI inference workloads"),
                    (4, "Intelligent infrastructure management: GPU-aware scheduling, cost-optimized model serving, and automated scaling based on queue depth and latency targets"),
                ],
                "personas": [("devops_engineer", 1.1), ("sre_platform_engineer", 1.1)],
            },
        ],
    },
    {
        "name": "ML & Foundation Model Operations",
        "description": "Assess your organization's maturity in operationalizing machine learning — from training pipeline health and GPU infrastructure to model lifecycle management and compute cost optimization.",
        "overall_weight": 0.85,
        "display_order": 4,
        "is_active": False,
        "is_gated": True,
        "gate_question": "Is your organization currently training, fine-tuning, or managing machine learning or foundation models in-house?",
        "questions": [
            {
                "text": "How mature is your organization's approach to operationalizing machine learning — moving models from development to production reliably?",
                "weight": 2.0,
                "general": True,
                "display_order": 1,
                "context_tags": [],
                "options": [
                    (1, "We have no formal process — models are deployed manually with no standardization"),
                    (2, "We have ad-hoc deployment processes for some models, but no consistent MLOps practices"),
                    (3, "Standardized MLOps pipelines exist for major models with version control and basic monitoring"),
                    (4, "Full MLOps maturity: automated training, evaluation, deployment, monitoring, and retraining pipelines"),
                ],
                "personas": [],
            },
            {
                "text": "How does your organization manage and track the cost of ML compute (GPU/TPU/CPU clusters)?",
                "weight": 1.5,
                "general": True,
                "display_order": 2,
                "context_tags": [],
                "options": [
                    (1, "We don't track ML compute costs separately — it's part of the general cloud bill"),
                    (2, "High-level cost tracking by team or project, reviewed monthly"),
                    (3, "Per-job and per-model cost tracking with budget alerts"),
                    (4, "Real-time compute cost optimization: per-experiment cost attribution, idle GPU detection, spot instance orchestration, and cost-per-trained-model tracking"),
                ],
                "personas": [],
            },
            {
                "text": "How do you track, compare, and select ML experiments before promoting a model to production?",
                "weight": 1.5,
                "general": True,
                "display_order": 3,
                "context_tags": [],
                "options": [
                    (1, "We don't track experiments formally — results are in notebooks or spreadsheets"),
                    (2, "Some logging of metrics per experiment, but no centralized tracking"),
                    (3, "Experiment tracking platform in use with metric comparison and artifact storage"),
                    (4, "Full experiment lifecycle management: automated metric logging, model registry integration, reproducibility guarantees, and governance-based promotion policies"),
                ],
                "personas": [],
            },
            {
                "text": "How does your organization monitor ML model performance after deployment to production?",
                "weight": 1.0,
                "general": True,
                "display_order": 4,
                "context_tags": [],
                "options": [
                    (1, "We don't monitor models post-deployment — issues are found by end users"),
                    (2, "Basic uptime and API error rate monitoring only"),
                    (3, "Model performance metrics tracked (latency, throughput, accuracy on known test sets)"),
                    (4, "Full production model observability: concept drift detection, data quality monitoring, performance degradation alerting, and automated retraining triggers"),
                ],
                "personas": [],
            },
            {
                "text": "How do you monitor GPU utilization and efficiency during model training?",
                "weight": 2.0,
                "general": False,
                "display_order": 5,
                "context_tags": ["gpu", "cuda", "model_training", "nvidia"],
                "options": [
                    (1, "We don't monitor GPU utilization during training"),
                    (2, "Basic GPU utilization metrics available but not actively monitored"),
                    (3, "GPU utilization, memory usage, and job throughput tracked per training run"),
                    (4, "Full GPU observability: real-time utilization, memory efficiency, bottleneck detection, and automated alerts for idle or underutilized compute"),
                ],
                "personas": [("ml_ai_engineer", 1.2)],
            },
            {
                "text": "How do you manage model versioning, registration, and promotion through your ML lifecycle?",
                "weight": 1.5,
                "general": False,
                "display_order": 6,
                "context_tags": [],
                "options": [
                    (1, "No formal versioning — models are saved as files with manual naming"),
                    (2, "Basic version control for model artifacts, but no formal registry"),
                    (3, "Centralized model registry with versioning and stage tracking (staging, production, archived)"),
                    (4, "Full model lifecycle management: automated registration, metadata tracking, lineage tracing, governance policies, and audit trails for every production change"),
                ],
                "personas": [("ml_ai_engineer", 1.2)],
            },
            {
                "text": "How do you ensure reproducibility of ML training runs?",
                "weight": 1.5,
                "general": False,
                "display_order": 7,
                "context_tags": [],
                "options": [
                    (1, "Reproducibility is not a priority — we can't reliably recreate past training results"),
                    (2, "Code is version-controlled, but data and environment versions are not consistently tracked"),
                    (3, "Code, data versions, and key hyperparameters are logged per run"),
                    (4, "Full reproducibility: code, data, environment (Docker/conda), hyperparameters, and random seeds captured per run with one-click rerun capability"),
                ],
                "personas": [("ml_ai_engineer", 1.2)],
            },
            {
                "text": "How integrated are your ML training pipelines with your standard CI/CD processes?",
                "weight": 1.0,
                "general": False,
                "display_order": 8,
                "context_tags": [],
                "options": [
                    (1, "ML pipelines are completely separate from software CI/CD"),
                    (2, "Some shared infrastructure, but ML pipelines are managed manually"),
                    (3, "ML pipelines are triggered automatically on code or data changes"),
                    (4, "Full ML CI/CD: automated training, evaluation, comparison against baseline, and deployment gating on model quality metrics"),
                ],
                "personas": [("ml_ai_engineer", 1.1), ("devops_engineer", 1.1)],
            },
            {
                "text": "How does your organization measure and optimize the ROI of ML compute investments?",
                "weight": 1.5,
                "general": False,
                "display_order": 9,
                "context_tags": [],
                "options": [
                    (1, "We don't measure ML compute ROI"),
                    (2, "High-level budget tracking — we know the total spend but not the value delivered"),
                    (3, "Cost-per-model or cost-per-experiment tracked alongside model business impact"),
                    (4, "Full ML investment optimization: compute cost attributed to business outcomes, automated rightsizing recommendations, and executive dashboards linking ML spend to product metrics"),
                ],
                "personas": [("cto_executive", 0.9), ("vp_engineering", 0.9)],
            },
            {
                "text": "How does your organization govern which ML models are deployed to production and who can access or modify them?",
                "weight": 1.5,
                "general": False,
                "display_order": 10,
                "context_tags": [],
                "options": [
                    (1, "No formal governance — any engineer can deploy a model"),
                    (2, "Informal review process before deployment"),
                    (3, "Defined approval workflow with documented owners and review criteria"),
                    (4, "Automated governance: model cards required, approval workflows enforced, access controls by model, and full audit trail from training to production"),
                ],
                "personas": [("cto_executive", 0.9), ("vp_engineering", 0.9)],
            },
            {
                "text": "How is your GPU and ML compute infrastructure managed and scaled?",
                "weight": 1.5,
                "general": False,
                "display_order": 11,
                "context_tags": ["gpu", "kubernetes", "cloud_compute", "aws", "gcp", "azure"],
                "options": [
                    (1, "Manual provisioning — engineers request compute ad-hoc"),
                    (2, "Fixed compute clusters with manual scaling when capacity runs out"),
                    (3, "Auto-scaling GPU clusters with queue-based job scheduling"),
                    (4, "Intelligent compute orchestration: multi-cloud GPU scheduling, spot/preemptible instance management, priority queuing, and cost-optimized autoscaling"),
                ],
                "personas": [("sre_platform_engineer", 1.1)],
            },
            {
                "text": "How do you monitor model serving infrastructure for reliability and performance?",
                "weight": 1.0,
                "general": False,
                "display_order": 12,
                "context_tags": [],
                "options": [
                    (1, "No dedicated monitoring for model serving — same as generic application monitoring"),
                    (2, "Basic uptime and latency monitoring for model endpoints"),
                    (3, "Model-specific SLOs for latency and throughput with alerting"),
                    (4, "Full model serving observability: per-model SLOs, traffic-based autoscaling, A/B traffic splitting, shadow mode deployment, and automated rollback on performance degradation"),
                ],
                "personas": [("sre_platform_engineer", 1.1), ("devops_engineer", 1.1)],
            },
            {
                "text": "How do developers in your organization consume ML models in production applications?",
                "weight": 1.0,
                "general": False,
                "display_order": 13,
                "context_tags": [],
                "options": [
                    (1, "Models are accessed through ad-hoc scripts or direct file loading"),
                    (2, "REST APIs exist for some models, but discovery and documentation are poor"),
                    (3, "Centralized model serving platform with versioned APIs and SDK"),
                    (4, "Self-service ML platform: model catalog with documentation, versioned APIs, usage tracking, and automated deprecation notices"),
                ],
                "personas": [("software_developer", 1.0)],
            },
        ],
    },
    {
        "name": "Security & DevSecOps",
        "description": "Assess your organization's maturity in integrating security into development, operations, and cloud infrastructure management.",
        "overall_weight": 1.0,
        "display_order": 5,
        "is_active": True,
        "is_gated": False,
        "gate_question": None,
        "questions": [
            {
                "text": "How is security currently integrated into your software development lifecycle (SDLC)?",
                "weight": 2.0,
                "general": True,
                "display_order": 1,
                "context_tags": [],
                "options": [
                    (1, "Security is reviewed only at release or after deployment"),
                    (2, "Penetration testing and security reviews happen, but late in the cycle"),
                    (3, "Security scanning integrated into CI/CD; developers get feedback during development"),
                    (4, "Shift-left security is the standard: SAST, DAST, SCA, and IaC scanning run on every commit with developer-facing remediation guidance"),
                ],
                "personas": [],
            },
            {
                "text": "How do you manage vulnerabilities in your software supply chain (open source dependencies, container images)?",
                "weight": 1.5,
                "general": True,
                "display_order": 2,
                "context_tags": [],
                "options": [
                    (1, "We don't actively track open-source vulnerabilities"),
                    (2, "Scans run occasionally with slow, manual remediation"),
                    (3, "Automated SCA scans with defined SLAs for remediation by severity"),
                    (4, "Continuous SCA with auto-remediation PRs, SBOM generation, and runtime enforcement of approved packages"),
                ],
                "personas": [],
            },
            {
                "text": "How does your organization detect and respond to threats in your cloud or production environment at runtime?",
                "weight": 1.5,
                "general": True,
                "display_order": 3,
                "context_tags": [],
                "options": [
                    (1, "No runtime security monitoring"),
                    (2, "Basic WAF and network-level controls only"),
                    (3, "Agent-based runtime monitoring for known threat signatures"),
                    (4, "Behavioral-based workload protection with AI-powered threat detection, anomaly identification, and automated response playbooks"),
                ],
                "personas": [],
            },
            {
                "text": "How do you manage cloud security posture (misconfiguration detection, identity and entitlement management)?",
                "weight": 1.0,
                "general": True,
                "display_order": 4,
                "context_tags": [],
                "options": [
                    (1, "We rely on cloud provider defaults with no active posture management"),
                    (2, "Periodic manual security audits"),
                    (3, "CSPM tool in place with regular review cycles"),
                    (4, "Continuous CSPM and CIEM with automated drift detection, policy enforcement, and compliance reporting"),
                ],
                "personas": [],
            },
            {
                "text": "How mature is your organization's approach to security compliance and regulatory requirements?",
                "weight": 2.0,
                "general": False,
                "display_order": 5,
                "context_tags": [],
                "options": [
                    (1, "No formal compliance program"),
                    (2, "Compliance requirements addressed reactively when audits occur"),
                    (3, "Defined compliance program with regular assessments and documented controls"),
                    (4, "Continuous compliance monitoring with automated evidence collection, audit-ready reporting, and proactive gap remediation"),
                ],
                "personas": [("ciso_vp_security", 1.2)],
            },
            {
                "text": "How does your organization manage the security of APIs and applications exposed to external users or partners?",
                "weight": 1.5,
                "general": False,
                "display_order": 6,
                "context_tags": [],
                "options": [
                    (1, "No application-level security controls beyond network firewalls"),
                    (2, "Basic WAF rules and rate limiting"),
                    (3, "API security scanning and access controls with regular review"),
                    (4, "Full API and application protection: behavioral threat detection, automated bot management, API discovery, and real-time abuse prevention"),
                ],
                "personas": [("ciso_vp_security", 1.2)],
            },
            {
                "text": "How does your organization manage secrets, credentials, and access keys?",
                "weight": 1.0,
                "general": False,
                "display_order": 7,
                "context_tags": [],
                "options": [
                    (1, "Secrets are stored in code or shared via email and messaging tools"),
                    (2, "Centralized secrets manager in place but not consistently used"),
                    (3, "Secrets manager enforced for all production systems with rotation policies"),
                    (4, "Automated secret scanning in CI/CD, zero-trust secrets management, automated rotation, and full audit logging"),
                ],
                "personas": [("ciso_vp_security", 1.1), ("security_engineer", 1.1)],
            },
            {
                "text": "At what stage does security scanning occur in your deployment pipeline?",
                "weight": 1.5,
                "general": False,
                "display_order": 8,
                "context_tags": [],
                "options": [
                    (1, "Post-deployment only, or never"),
                    (2, "Pre-release (staging or QA) only"),
                    (3, "CI pipeline on every PR or merge"),
                    (4, "Pre-commit hooks, CI pipeline scanning, and continuous runtime scanning"),
                ],
                "personas": [("security_engineer", 1.2)],
            },
            {
                "text": "How are security findings from scanning tools tracked and remediated?",
                "weight": 1.0,
                "general": False,
                "display_order": 9,
                "context_tags": [],
                "options": [
                    (1, "Findings are generated but not systematically tracked or actioned"),
                    (2, "Findings reviewed manually by the security team periodically"),
                    (3, "Findings ticketed with assigned owners and SLA-based remediation"),
                    (4, "Automated vulnerability management: findings triaged by severity and context, routed to owning teams, tracked to closure with SLA enforcement"),
                ],
                "personas": [("security_engineer", 1.1), ("devops_engineer", 1.1)],
            },
            {
                "text": "How is container and Kubernetes security currently managed?",
                "weight": 1.0,
                "general": False,
                "display_order": 10,
                "context_tags": ["kubernetes", "containers", "docker"],
                "options": [
                    (1, "No container-specific security controls"),
                    (2, "Basic image scanning before deployment"),
                    (3, "Image scanning, admission control policies, and network policies in place"),
                    (4, "Full container security: image signing, runtime behavioral monitoring, automated policy enforcement, and continuous compliance scanning of running workloads"),
                ],
                "personas": [("devops_engineer", 1.1), ("sre_platform_engineer", 1.1)],
            },
            {
                "text": "How does your engineering culture approach security ownership?",
                "weight": 1.5,
                "general": False,
                "display_order": 11,
                "context_tags": [],
                "options": [
                    (1, "Security is solely the security team's responsibility; developers are not involved"),
                    (2, "Security requirements are handed off to developers at the end of sprints"),
                    (3, "Security champions embedded in engineering teams with shared ownership"),
                    (4, "Security is a shared engineering responsibility: developers own remediation, security provides tooling and guardrails, and security metrics are part of engineering KPIs"),
                ],
                "personas": [("cto_executive", 0.9), ("vp_engineering", 0.9)],
            },
            {
                "text": "How confident are you in your ability to identify and fix common security vulnerabilities in your code?",
                "weight": 1.0,
                "general": False,
                "display_order": 12,
                "context_tags": [],
                "options": [
                    (1, "I rely entirely on the security team to identify vulnerabilities"),
                    (2, "I am aware of common vulnerabilities but have limited tooling support"),
                    (3, "Security linting and IDE plugins flag common issues during development"),
                    (4, "Security feedback is integrated into my IDE, PR review, and CI pipeline with context-aware guidance for every flagged issue"),
                ],
                "personas": [("software_developer", 1.0)],
            },
        ],
    },
]
